attempt to use System.Text.Json instead of Newtonsoft.Json
JsonSerializationException: Unable to find a constructor to use for type System.Text.Json.Nodes.JsonArray.